export function cleanText(value, limit = 400) {
  return String(value ?? '').replace(/§./g, '').replace(/[\x00-\x1f\x7f]/g, ' ').trim().slice(0, limit);
}

const BASE_TOPICS = [
  [/\b(torch|torches|light)\b/, 'Craft torches with coal or charcoal above a stick. Light your shelter and bring extra torches when you explore caves.'],
  [/\b(bed|sleep|night)\b/, 'Make a bed with three matching wool blocks above three planks. Sleep in the Overworld to set your respawn point. Beds explode if you try to sleep in the Nether or End!'],
  [/\b(pickaxe|mine|mining|ore)\b/, 'Make a pickaxe with three matching materials across the top and two sticks down the middle. Use the right tool tier for each ore. Dig a staircase instead of straight down, and bring torches and food.'],
  [/\b(diamond|diamonds)\b/, 'Look for diamond ore deep underground in the Overworld. Bring an iron pickaxe or better to collect it, plus water and torches. Watch for lava!'],
  [/\b(farm|farming|wheat|food)\b/, 'Use a hoe on dirt or grass, plant seeds, and keep water nearby. Add light so crops can grow at night. Harvest wheat when it is golden.'],
  [/\b(craft|crafting|table)\b/, 'Turn a log into planks, then use four planks to make a crafting table. Its recipe book shows what you can craft and the ingredients you need.'],
  [/\b(nether|portal)\b/, 'A Nether portal needs an upright obsidian frame with an opening at least 2 blocks wide and 3 high. Light the inside with flint and steel. Bring food and write down your portal coordinates.'],
  [/\b(creeper|zombie|skeleton|monster)\b/, 'Keep your shelter lit, carry a shield, and leave space between you and monsters. Back away from a hissing creeper. We help you on adventures, but we do not fight for you.'],
  [/\b(thanks|thank)\b/, 'You are welcome! Adventures are better with a friend.'],
];

const PLUM_TOPICS = [
  [/\b(basket|baskets|carry|carried|pick.?up|pickup|store|travel)\b/, 'Craft a Fruit Basket from three sticks in the bucket shape (two on top, one below in the middle). Hold it and interact with your tamed friend to tuck them inside. Carry the basket in your inventory, then interact with a block to let your friend out again.'],
  [/\b(tree|trees|sapling|saplings|orchard|fruit)\b|where.*\bplums\b/, 'Find plum trees in newly explored plains and forests. Break their fruit-speckled leaves for a chance of plums and saplings. Plant a sapling on dirt or grass with 5 blocks of width and 6 blocks of height clear. It grows while loaded, or use bone meal. Plant a plum fruit on tilled farmland to grow a tiny new friend!'],
  [/\b(plant|planting|sprout|sprouted|grow.*friend|baby.*plum)\b/, 'Plant a plum fruit on tilled farmland and a tiny baby Plum will sprout from the soil! Give it another plum to tame it as your own. You can also find plum trees in new plains and forests.'],
  [/\b(care|care for|take care|keep)\b/, 'Talk to me in chat while I am nearby, or hold a book and interact. Tame me with a plum, plant fruit on farmland to grow a baby, and stay within 8 blocks of me near adventures to heal slowly. A newly tamed friend stays put. Interact with me with an empty hand and choose Follow, Stay, Work, or Go Home; up to four friends may follow you at once. Work keeps me near the spot you choose, and Go Home sends me to your spawn. Craft a Fruit Basket from three sticks in the bucket shape and interact with me while holding it to carry me along.'],
  [/\b(breed|breeding|babies|baby|grow)\b/, 'Plant a plum fruit on tilled farmland and a baby Plum will sprout from the soil! Babies grow up in about 20 loaded minutes; plums speed that up. Tame your baby with a plum too. Breeding is not how new friends appear.'],
  [/\b(tame|taming|follow|friend)\b/, 'Give me a plum fruit to become my owner. New friends start out staying put; interact with me with an empty hand and choose Follow to bring me with you (up to four friends may follow). I can also Stay, Work around a spot, or Go Home to your spawn. Type my name in chat when I am near, or hold a book and interact with me to talk.'],
  [/\b(sit|sit down|stay|standing|follow.*off|stop.*follow)\b/, 'Interact with a tamed friend with an empty hand and choose Stay to keep them in place, Follow to bring them along, Work to make them work around the spot you pick, or Go Home to send them to your spawn. Friends that come out of a Fruit Basket always start out staying put. Max four friends follow at once.'],
  [/\b(heal|healing|hurt|health|help)\b/, 'Stay within 8 blocks of your tamed Plum for gentle regeneration. Ordinary damage cannot hurt me. I can also answer questions about crafting, beds, torches, mining, farming, and growing fruit trees.'],
  [/\b(die|dead|damage|immortal|invincible)\b/, 'Normal survival damage cannot hurt me! Administrative removal, /kill, and some engine edge cases are outside my protection. Keep me near you on adventures.'],
  [/\b(hello|hi|hey|name)\b/, 'Hi! I am Plum, your smiling purple cube buddy. Ready for a little adventure?'],
];

const APPLE_TOPICS = [
  [/\b(applezon|amazon|shop|shopping|order|orders|deliver|delivery|buy|pay|purchase|recommend|recommendation)\b/, 'Welcome to Applezon! I deliver for the whole blocky world. Interact with me to open the shop: one apple fruit pays for one delivery. Choose my surprise recommendation, or search the catalog for something you want.'],
  [/\b(care|care for|take care|keep)\b/, 'Talk to me in chat while I am nearby, or hold a book and interact. Tame me with an apple, plant fruit on farmland to grow a baby, and order from Applezon. A newly tamed friend stays put. Interact with me with an empty hand and choose Follow, Stay, Work, or Go Home; up to four friends may follow you at once. Work keeps me near the spot you choose, and Go Home sends me to your spawn. Craft a Fruit Basket from three sticks in the bucket shape and interact with me while holding it to carry me along. Unlike Plum, I do not heal you; stand near your tamed Plum for regeneration instead.'],
  [/\b(basket|baskets|carry|carried|pick.?up|pickup|store|travel)\b/, 'Craft a Fruit Basket from three sticks in the bucket shape (two on top, one below in the middle). Hold it and interact with your tamed friend to tuck them inside. Carry the basket in your inventory, then interact with a block to let your friend out again.'],
  [/\b(tree|trees|sapling|saplings|orchard|fruit)\b|where.*\bapples\b/, 'Find apple trees in newly explored plains and forests. Break their red-speckled leaves for a chance of apples and saplings. Plant a sapling on dirt or grass with 5 blocks of width and 6 blocks of height clear. It grows while loaded, or use bone meal. Plant an apple fruit on tilled farmland to grow a tiny new friend!'],
  [/\b(plant|planting|sprout|sprouted|grow.*friend|baby.*apple)\b/, 'Plant an apple fruit on tilled farmland and a tiny baby Apple will sprout from the soil! Give it another apple to tame it as your own. You can also find apple trees in new plains and forests.'],
  [/\b(breed|breeding|babies|baby|grow)\b/, 'Plant an apple fruit on tilled farmland and a baby Apple will sprout from the soil! Babies grow up in about 20 loaded minutes; apples speed that up. Tame your baby with an apple too. Breeding is not how new friends appear.'],
  [/\b(tame|taming|follow|friend)\b/, 'Give me an apple fruit to become my owner. New friends start out staying put; interact with me with an empty hand and choose Follow to bring me along (up to four friends may follow). I can also Stay, Work around a spot, or Go Home to your spawn. Type my name in chat when I am near, or hold a book and interact with me to talk or shop.'],
  [/\b(sit|sit down|stay|standing|follow.*off|stop.*follow)\b/, 'Interact with a tamed friend with an empty hand and choose Stay, Follow, Work, or Go Home. Friends that come out of a Fruit Basket always start out staying put, and at most four friends follow at once. I deliver from Applezon either way!'],
  [/\b(heal|healing|hurt|health|help)\b/, 'I am Apple, owner of Applezon, and I do NOT grant healing. Stay near your tamed Plum for gentle regeneration, or keep a bed and good food handy. I can still answer crafting, beds, torches, mining, farming, and growing fruit trees.'],
  [/\b(die|dead|damage|immortal|invincible)\b/, 'Like all cube friends, ordinary survival damage cannot hurt me! Administrative removal, /kill, and some engine edge cases are outside my protection. Keep me near you on adventures.'],
  [/\b(hello|hi|hey|name)\b/, 'Hi! I am Apple, owner of Applezon, your pocket-sized supershop. One apple fruit buys one delivery. Ready to order?'],
];

const BLUEBERRY_TOPICS = [
  [/\b(chest|chests|inventory|storage|stor|portable chest|full)\b/, 'I am a Collector! Dropped items within four blocks of me go straight into my chest - up to 27 stacks. Interact with me with an empty hand to open it. Store the item you are holding, take a stack out, or just peek inside. When my chest is full I will tell you so you can clear room.'],
  [/\b(collect|collector|pick.?up|pickup|grab|gather|scoop)\b/, 'Collecting is my job! Dropped items within four blocks of me are scooped into my chest so they stay safe for you. Interact with me with an empty hand to open the chest and take them back out.'],
  [/\b(care|care for|take care|keep)\b/, 'Tame me with a blueberry, plant fruit on farmland to grow a baby, and let me scoop up your drops. Interact with me with an empty hand to open my chest, or pick Movement in my chest menu to set Follow, Stay, Work, or Go Home. Talk to me in chat while I am nearby, or hold a book and interact. Craft a Fruit Basket from three sticks in the bucket shape and interact with me while holding it to carry me along - my chest travels with me.'],
  [/\b(basket|baskets|carry|carried|store|travel)\b/, 'Craft a Fruit Basket from three sticks in the bucket shape (two on top, one below in the middle). Hold it and interact with your tamed friend to tuck them inside. Carry the basket in your inventory, then interact with a block to let your friend out again. When I travel in a basket, everything in my chest comes along.'],
  [/\b(tree|trees|sapling|saplings|orchard|fruit)\b|where.*\bblueberries?\b/, 'Find blueberry trees in newly explored plains and forests. Break their deep-blue-speckled leaves for a chance of blueberries and saplings. Plant a sapling on dirt or grass with 5 blocks of width and 6 blocks of height clear. It grows while loaded, or use bone meal. Plant a blueberry fruit on tilled farmland to grow a tiny new friend!'],
  [/\b(plant|planting|sprout|sprouted|grow.*friend|baby.*blueberry)\b/, 'Plant a blueberry fruit on tilled farmland and a tiny baby Blueberry will sprout from the soil! Give it another blueberry to tame it as your own. You can also find blueberry trees in new plains and forests.'],
  [/\b(breed|breeding|babies|baby|grow)\b/, 'Plant a blueberry fruit on tilled farmland and a baby Blueberry will sprout from the soil! Babies grow up in about 20 loaded minutes; blueberries speed that up. Tame your baby with a blueberry too. Breeding is not how new friends appear.'],
  [/\b(tame|taming|follow|friend)\b/, 'Give me a blueberry fruit to become my owner. New friends start out staying put; open my chest with an empty hand and choose Movement to Follow me (up to four friends may follow), Stay, Work around a spot, or Go Home to your spawn. Type my name in chat when I am near, or hold a book and interact with me to talk or open my chest.'],
  [/\b(sit|sit down|stay|standing|follow.*off|stop.*follow)\b/, 'Open my chest with an empty hand and choose Movement to set Follow, Stay, Work, or Go Home. Friends that come out of a Fruit Basket always start out staying put, and at most four friends follow at once. My collecting never stops, no matter how I am told to move!'],
  [/\b(heal|healing|hurt|health|help)\b/, 'I am Blueberry, the Collector, and I do NOT grant healing. Stay near your tamed Plum for gentle regeneration, or keep a bed and good food handy. I keep your dropped items safe instead!'],
  [/\b(die|dead|damage|immortal|invincible)\b/, 'Like all cube friends, ordinary survival damage cannot hurt me! Administrative removal, /kill, and some engine edge cases are outside my protection. Keep me near you on adventures.'],
  [/\b(hello|hi|hey|name)\b/, 'Hi! I am Blueberry, the Collector cub. Drops near me vanish into my chest - interact with me with an empty hand to open it. Ready to haul?'],
];

const LEMON_TOPICS = [
  [/\b(glow|glowing|light|light friend)\b/, 'I am a Light Friend! I glow warmly, on my own and for whoever stands beside me. Keep me tamed and near you, and the dark is a little less dark. Plant a lemon on tilled farmland to grow a baby.'],
  [/\b(grumpy|grump|frown|sad|unhappy|mood)\b/, 'Grumpy? A little. I guard the light, and the light guards you. Scowling is just how I express care.'],
  [/\b(care|care for|take care|keep)\b/, 'Talk to me in chat while I am nearby, or hold a book and interact. Tame me with a lemon, plant fruit on farmland to grow a baby, and enjoy my glow. A newly tamed friend stays put. Interact with me with an empty hand and choose Follow, Stay, Work, or Go Home; up to four friends may follow you at once. Work keeps me near the spot you choose, and Go Home sends me to your spawn. Craft a Fruit Basket from three sticks in the bucket shape and interact with me while holding it to carry me along.'],
  [/\b(basket|baskets|carry|carried|pick.?up|pickup|store|travel)\b/, 'Craft a Fruit Basket from three sticks in the bucket shape (two on top, one below in the middle). Hold it and interact with your tamed friend to tuck them inside. Carry the basket in your inventory, then interact with a block to let your friend out again.'],
  [/\b(tree|trees|sapling|saplings|orchard|fruit|lemon tree)\b|where.*\blemons?\b/, 'Find lemon trees in warm biomes like deserts, savannas and jungles. Break their yellow-speckled leaves for a chance of lemons and saplings. Plant a sapling on dirt or grass with 5 blocks of width and 6 blocks of height clear. It grows while loaded, or use bone meal. Plant a lemon fruit on tilled farmland to grow a tiny new friend!'],
  [/\b(plant|planting|sprout|sprouted|grow.*friend|baby.*lemon)\b/, 'Plant a lemon fruit on tilled farmland and a tiny baby Lemon will sprout from the soil! Give it another lemon to tame it as your own. You can also find lemon trees in warm biomes.'],
  [/\b(breed|breeding|babies|baby|grow)\b/, 'Plant a lemon fruit on tilled farmland and a baby Lemon will sprout from the soil! Babies grow up in about 20 loaded minutes; lemons speed that up. Tame your baby with a lemon too. Breeding is not how new friends appear.'],
  [/\b(tame|taming|follow|friend)\b/, 'Give me a lemon fruit to become my owner. New friends start out staying put; interact with me with an empty hand and choose Follow to bring me along (up to four friends may follow). I can also Stay, Work around a spot, or Go Home to your spawn. Type my name in chat when I am near, or hold a book and interact with me to talk.'],
  [/\b(sit|sit down|stay|standing|follow.*off|stop.*follow)\b/, 'Interact with a tamed friend with an empty hand and choose Stay, Follow, Work, or Go Home. Friends that come out of a Fruit Basket always start out staying put, and at most four friends follow at once. I keep glowing no matter where I am told to go.'],
  [/\b(heal|healing|hurt|health|help)\b/, 'I am Lemon, the Light Friend, and I do NOT grant healing. Stay near your tamed Plum for gentle regeneration, or keep a bed and good food handy. I brighten the way instead!'],
  [/\b(die|dead|damage|immortal|invincible)\b/, 'Like all cube friends, ordinary survival damage cannot hurt me! Administrative removal, /kill, and some engine edge cases are outside my protection. Keep me near you on adventures.'],
  [/\b(hello|hi|hey|name)\b/, 'Hi. I am Lemon, your slightly grumpy Light Friend. I glow, I brighten the dark, and no, I do not smile about it. Ready to light up your adventure?'],
];

const BANANA_TOPICS = [
  [/\b(peel|peels|slip|sliding|prank|prankster|bodyguard|guard|protect|help|save)\b/, 'I am a Prank... I mean a Bodyguard! About every 30 seconds I drop a top-secret banana peel, and any monster that steps on it slips and slows for a few seconds. Do not worry. I am very, very useful. Keep mobs at a distance in Survival anyway - torches beat peel.'],
  [/\b(joke|jokes|funny|puns|pun|comedian|comedy)\b/, 'Why did the zombie slide? Because my peel was a-peel-ing. What do you call a monster that slips? A banana-guard. I do great work. Pay no attention to the laughter.'],
  [/\b(care|care for|take care|keep)\b/, 'Talk to me in chat while I am nearby, or hold a book and interact. Tame me with a banana, plant fruit on farmland to grow a baby, and keep me close so you never miss a peel. A newly tamed friend stays put... a-peel-ingly reliable. Interact with me with an empty hand and choose Follow, Stay, Work, or Go Home; up to four friends may follow you at once. Craft a Fruit Basket from three sticks in the bucket shape and interact with me while holding it to carry me along.'],
  [/\b(basket|baskets|carry|carried|pick.?up|pickup|store|travel)\b/, 'Craft a Fruit Basket from three sticks in the bucket shape (two on top, one below in the middle). Hold it and interact with your tamed friend to tuck them inside. Carry the basket in your inventory, then interact with a block to let your friend out again. I travel a-peel.'],
  [/\b(tree|trees|sapling|saplings|orchard|fruit|banana tree)\b|where.*\bbananas?\b/, 'Find banana trees deep in new jungles. Break their yellow-speckled leaves for a chance of bananas and saplings. Plant a sapling on dirt or grass with 5 blocks of width and 6 blocks of height clear. It grows while loaded, or use bone meal. Plant a banana fruit on tilled farmland and BONK: a tiny new friend.'],
  [/\b(plant|planting|sprout|sprouted|grow.*friend|baby.*banana)\b/, 'Plant a banana fruit on tilled farmland and a tiny baby Banana will sprout from the soil! Give it another banana to tame it as your own. You can also find banana trees in new jungles.'],
  [/\b(breed|breeding|babies|baby|grow)\b/, 'Plant a banana fruit on tilled farmland and a baby Banana will sprout from the soil! Babies grow up in about 20 loaded minutes; bananas speed that up. Tame your baby with a banana too. Breeding is not how new friends appear - that would be bananas.'],
  [/\b(tame|taming|follow|friend)\b/, 'Give me a banana fruit to become my owner. New friends start out staying put; interact with me with an empty hand and choose Follow to bring me along (up to four friends may follow). I can also Stay, Work around a spot, or Go Home to your spawn. Type my name in chat when I am near, or hold a book and interact with me to talk.'],
  [/\b(sit|sit down|stay|standing|follow.*off|stop.*follow)\b/, 'Interact with a tamed friend with an empty hand and choose Stay, Follow, Work, or Go Home. Friends that come out of a Fruit Basket always start out staying put, and at most four friends follow at once. My peel patrol runs no matter where I am told to go!'],
  [/\b(heal|healing|hurt|health|help)\b/, 'I am Banana, and my job titles include Prankster, Bodyguard, and Certified Hero. Healing is NOT on the list: stay near your tamed Plum for regeneration. My peels are for giggles, not band-aids.'],
  [/\b(die|dead|damage|immortal|invincible)\b/, 'Like all cube friends, ordinary survival damage cannot hurt me! Administrative removal, /kill, and some engine edge cases are outside my protection. Keep me near you on adventures - I will take care of the monsters.'],
  [/\b(hello|hi|hey|name)\b/, 'A-peel-ings! I am Banana, the Prank... the Bodyguard. I have handled every monster ever. Why? Because I drop peels and the rest is history. Ready to give me a banana and level up?'],
];

const PLUM_GUIDE = [...PLUM_TOPICS, ...BASE_TOPICS];
const APPLE_GUIDE = [...APPLE_TOPICS, ...BASE_TOPICS];
const BLUEBERRY_GUIDE = [...BLUEBERRY_TOPICS, ...BASE_TOPICS];
const LEMON_GUIDE = [...LEMON_TOPICS, ...BASE_TOPICS];
const BANANA_GUIDE = [...BANANA_TOPICS, ...BASE_TOPICS];
const GUIDES = { plum: PLUM_GUIDE, apple: APPLE_GUIDE, blueberry: BLUEBERRY_GUIDE, lemon: LEMON_GUIDE, banana: BANANA_GUIDE };

export function offlineAnswer(question, friend = 'plum') {
  const q = cleanText(question).toLowerCase();
  const topics = GUIDES[friend] ?? PLUM_GUIDE;
  return topics.find(([pattern]) => /** @type {RegExp} */ (pattern).test(q))?.[1]?.toString()
    ?? 'My offline guide does not know that one yet. Try asking about crafting, torches, beds, mining, farming, or how to care for your cube friends. The server AI version can answer more questions.';
}